version: "3.7"
services:
  joinmyproject:
    container_name: joinmyproject
    restart: unless-stopped
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  letsproxy:
    image: neilpang/letsproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs
      - ./proxy/acme:/acmecerts
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/stream.d:/etc/nginx/stream.d
      - ./proxy/dhparam:/etc/nginx/dhparam
    network_mode: "host"
